name: drupal

type: php:5.6

build:
    flavor: drupal

dependencies:
    php:
        drush/drush: "~7.0"

relationships:
    database: "mysql:mysql"
    solr: "solr:solr"
    redis: "redis:redis"

runtime:
    extensions:
        - redis
        - xsl
    disabled_extensions:
        - sqlite3
        - pdo_sqlite

web:
    document_root: "/web"
    passthru: "/index.php"

disk: 2048

mounts:
    "/platform/files": "shared:files/files"
    "/private": "shared:files/private"

hooks:
    build: |
        set -e
        drush pm-download registry_rebuild
        drush cache-clear drush
        drush make ./src/drupal.make.yml ./web
        drush make --no-core --concurrency=3 --no-recursion --contrib-destination=. ./src/elife_profile/elife_profile.make.yml ./src/elife_profile
        npm install --prefix ./src/elife_profile/libraries/elife-eif-schema/
        composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader
        ln -s "../../src/elife_profile" "./web/profiles/"
        ln -s "../../../src/settings.php" "./web/sites/default/"
        ln -s "../../../platform/files" "web/sites/default/files"
        cp platform/local.settings.php .
    deploy: |
        set -e
        cd web
        drush registry-rebuild
        drush updatedb --yes
        drush features-revert-all --yes
        drush elife-environment-modules

crons:
    drupal:
        spec: "*/10 * * * *"
        cmd: "./run-cron.sh"
