<?php
/**
 * @file
 * Code for the eLife: Events feature.
 */

include_once 'elife_events.features.inc';

/**
 * Implements template_preprocess_node().
 */
function elife_events_preprocess_node(&$variables) {
  if ('elife_event' === $variables['type'] && 'teaser' === $variables['view_mode']) {
    drupal_add_css(drupal_get_path('module', 'elife_events') . '/css/event-teaser.css');
  }
}

/**
 * Implements hook_elife_xmlsitemap_custom_links().
 */
function elife_events_elife_xmlsitemap_custom_links() {
  return [
    'elife_events' => [
      'events',
    ],
  ];
}
