<?php
/**
 * @file
 * Code for the eLife: Events feature.
 */

include_once 'elife_events.features.inc';

/**
 * Implements hook_node_view().
 */
function elife_events_node_view($node, $view_mode, $langcode) {
  if ('elife_event' === $node->type && 'teaser' === $view_mode) {
    $node->content['#attached']['css'][] = drupal_get_path('module', 'elife_events') . '/css/event-teaser.css';
  }
}

/**
 * Implements hook_elife_xmlsitemap_custom_links().
 */
function elife_events_elife_xmlsitemap_custom_links() {
  return [
    'elife_events' => [
      'events',
    ],
  ];
}
