<?php
/**
 * @file
 * Code for the eLife: Users feature.
 */

include_once 'elife_users.features.inc';

/**
 * Implements hook_realname_alter().
 */
function elife_users_realname_alter(&$realname, $account) {
  if (1 == $account->uid) {
    $realname = 'Administrator'; // The admin user shouldn't have a real name.
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for user_profile_form().
 */
function elife_users_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['#entity']) && 1 == $form['#entity']->uid) {
    // Hide the fields, as the admin user shouldn't have a real name.
    $form['field_elife_u_first_name']['#access'] = FALSE;
    $form['field_elife_u_last_name']['#access'] = FALSE;
  }
}

/**
 * Implements hook_features_post_restore().
 */
function elife_users_features_post_restore($op, $items) {
  if ('disable' !== $op && !empty($items['elife_users'])) {
    // Give user 1 the Administrator role.
    user_multiple_role_edit([1], 'add_role', variable_get('user_admin_role'));
  }
}
