<?php
/**
 * @file
 * Code for the eLife: Search feature.
 */

include_once 'elife_search.features.inc';

/**
 * Implements hook_menu().
 */
function elife_search_menu() {
  return [
    'browse' => [
      'title' => 'Browse articles',
      'access callback' => TRUE,
      'page callback' => '_elife_search_redirect',
      'type' => MENU_CALLBACK,
    ],
  ];
}

/**
 * Implements hook_search_api_solr_documents_alter().
 */
function elife_search_search_api_solr_documents_alter(array &$documents, SearchApiIndex $index, array $items) {
  foreach ($documents as $document) {
    // Remove all categories that aren't display channels.
    $field = $document->getField('im_field_elife_a_versions$field_elife_a_category');

    if (!$field) {
      continue;
    }

    foreach ($field['value'] as $i => $category_id) {
      $term = taxonomy_term_load($category_id);

      if ('elife_categories' !== $term->vocabulary_machine_name) {
        continue;
      }

      if ('display-channel' !== $term->field_elife_category_type[LANGUAGE_NONE][0]['value']) {
        unset($field['value'][$i]);
      }

      $document->setField('im_field_elife_a_versions$field_elife_a_category', $field['value'], $field['boost']);
    }
  }
}

function _elife_search_redirect() {
  drupal_goto('elife/search');
}

/**
 * Implements hook_form_alter().
 */
function elife_search_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ('elife_search' === $form_state['view']->name) {
    $form['keyword']['#attributes'] = ['placeholder' => t('Search for...')];
  }
}

/**
 * Implements hook_facet_items_alter().
 */
function elife_search_facet_items_alter(&$build, &$settings) {
  if ('field_elife_a_versions:field_elife_a_category' !== $settings->facet) {
    return;
  }

  $adapter = facetapi_adapter_load($settings->searcher);
  $facet = facetapi_facet_load($settings->facet, $settings->searcher);
  $items = $adapter->getActiveItems($facet);

  $item_values = array();

  foreach ($items as $item) {
    $item_values[] = $item['value'];
  }

  $is_all_link_active = count($items) == 0;
  $all_link_path = $adapter->getFacetPath($facet, $item_values, TRUE);
  $all_link_query = $adapter->getQueryString($facet, $item_values, TRUE);

  $build['All'] = array(
    '#markup' => t('All'),
    '#path' => $all_link_path,
    '#html' => FALSE,
    '#count' => NULL,
    '#indexed_value' => 'All',
    '#active' => $is_all_link_active,
    '#item_parents' => array(),
    '#item_children' => array(),
    '#taxonomy_weight' => 1000,
    '#query' => $all_link_query,
  );
}
