<?php

/**
 * Get list of simple pages.
 *
 * @return array
 *   Array of pages, keyed by path, containing 'title' and 'template'.
 */
function elife_simple_pages() {
  return [
    'terms-and-conditions-of-use' => [
      'title' => 'Terms and conditions of use',
      'template' => 'terms_and_conditions_of_use',
    ],
    'privacy-policy' => [
      'title' => 'Privacy policy',
      'template' => 'privacy_policy',
    ],
    'contact' => [
      'title' => 'Contact',
      'template' => 'contact',
    ],
    'alerts-and-feeds' => [
      'title' => 'Alerts and feeds',
      'template' => 'alerts_and_feeds',
    ],
    'received-thanks' => [
      'title' => 'Received, thanks!',
      'template' => 'received_thanks',
    ],
    'who-we-work-with' => [
      'title' => 'Who we work with',
      'template' => 'who_we_work_with',
    ],
    'highlights' => [
      'title' => 'Highlights of the journal',
      'template' => 'highlights',
    ],
    'highlights-confirmation' => [
      'title' => 'Order confirmed, thanks!',
      'template' => 'highlights_confirmation',
    ],
    'for-the-press' => [
      'title' => 'For the press',
      'template' => 'for_the_press',
    ],
    'resources' => [
      'title' => 'Resources',
      'template' => 'resources',
    ],
  ];
}

/**
 * Implements hook_menu().
 */
function elife_simple_pages_menu() {
  $menu = [];

  foreach (elife_simple_pages() as $path => $details) {
    if (empty($details['template'])) {
      continue;
    }

    $menu[$path] = [
      'title' => !empty($details['title']) ? $details['title'] : '',
      'page callback' => 'elife_simple_pages_view',
      'page arguments' => [$path, $details['template']],
      'access arguments' => ['access content'],
      'type' => MENU_CALLBACK,
    ];
  }

  return $menu;
}

/**
 * Implements hook_theme().
 */
function elife_simple_pages_theme($existing, $type, $theme, $path) {
  if ('module' !== $type) {
    return NULL;
  }

  $templates = [];

  $path = drupal_get_path('module', 'elife_simple_pages') . '/templates';

  foreach (elife_simple_pages() as $details) {
    if (empty($details['template'])) {
      continue;
    }

    $templates[$details['template']] = [
      'template' => $details['template'],
      'path' => $path,
    ];
  }

  return $templates;
}

/**
 * eLife Simple Page callback.
 */
function elife_simple_pages_view($path, $template) {
  if (current_path() !== $path) {
    return MENU_NOT_FOUND;
  }

  return '<div class="simple-content-wrapper">' . _pathologic_filter(theme($template), filter_format_load('elife_full_html'), NULL, LANGUAGE_NONE, NULL, NULL) . '</div>';
}

/**
 * Implements hook_elife_xmlsitemap_custom_links().
 */
function elife_simple_pages_elife_xmlsitemap_custom_links() {
  $links = [];

  foreach (array_keys(elife_simple_pages()) as $path) {
    $links[] = $path;
  }

  return ['elife_simple_pages' => $links];
}
