<?php
/**
 * @file
 * Code for the eLife: Article feature.
 */

include_once 'elife_article.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function elife_article_preprocess_node(&$variables) {
  $node = $variables['node'];

  $variables['submitted'] = t('Created !created-date and last modified on !changed-date', array(
    '!created-date' => format_date($node->created),
    '!changed-date' => format_date($node->changed),
  ));
}
