<?php
/**
 * @file
 * Code for the eLife: Collection feature.
 */

include_once 'elife_collection.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function elife_collection_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_elife_body_field().
 */
function elife_collection_elife_body_field() {
  return [
    'elife_collection' => 'field_elife_c_text',
  ];
}

/**
 * Implements hook_node_view().
 */
function elife_collection_node_view($node, $view_mode, $langcode) {
  if (
    'elife_collection' === $node->type
    &&
    in_array($view_mode, ['teaser', 'elife_teaser_compact'])
  ) {
    $node->content['#attached']['css'][] = drupal_get_path('module', 'elife_collection') . '/css/collection-teaser.css';
  }
}

/**
 * Implements template_preprocess_node().
 */
function elife_collection_preprocess_node(&$variables) {
  if ('elife_collection' === $variables['type']) {
    if (in_array($variables['view_mode'], ['teaser', 'elife_teaser_compact'])) {
      $curators = [];
      $curators_short = [];

      if (!empty($variables['elements']['#node']->field_elife_c_curators)) {
        foreach ($variables['elements']['#node']->field_elife_c_curators[LANGUAGE_NONE] as $curator) {
          $curator = node_load($curator['target_id']);

          if (empty($curator)) {
            continue;
          }

          $parts = [
            'first-name' => $curator->field_elife_pp_first_name[LANGUAGE_NONE][0]['safe_value'],
            'last-name' => $curator->field_elife_pp_last_name[LANGUAGE_NONE][0]['safe_value'],
          ];

          preg_match_all('/[A-Z]/', ucwords(strtolower($parts['first-name'])), $parts['initials']);
          $parts['initials'] = implode('', $parts['initials'][0]);

          $curators[] = [
            'data' => implode(' ', [$parts['first-name'], $parts['last-name']]),
            'class' => ['curator-list__item'],
          ];
          $curators_short[] = [
            'data' => implode(' ', [$parts['initials'], $parts['last-name']]),
            'class' => ['curator-list__item'],
          ];
        }
      }

      if (!empty($curators)) {
        $variables['elife_c_curators'] = theme('item_list', [
          'items' => $curators,
          'type' => 'ol',
          'title' => '',
          'attributes' => [
            'class' => [
              'collection-teaser__curator-list',
              'curator-list',
            ],
          ],
        ]);
      }

      if (!empty($curators_short)) {
        $variables['elife_c_curators_short'] = theme('item_list', [
          'items' => $curators_short,
          'type' => 'ol',
          'title' => '',
          'attributes' => [
            'class' => [
              'collection-teaser__curator-list',
              'curator-list',
            ],
          ],
        ]);
      }
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 */
function elife_collection_form_node_form_alter(&$form, &$form_state) {
  if ('elife_collection' === $form['#node']->type) {
    $form['field_elife_title']['#access'] = FALSE;
  }
}

/**
 * Implements hook_tokens().
 */
function elife_collection_tokens($type, $tokens, array $data = [], array $options = []) {
  $replacements = [];

  if ('node' === $type) {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'field-elife-c-articles:ids-with-collection':
          if ('elife_collection' !== $data['node']->type) {
            break;
          }
          $ids = [];
          if (!empty($data['node']->field_elife_c_articles[LANGUAGE_NONE])) {
            foreach ($data['node']->field_elife_c_articles[LANGUAGE_NONE] as $article) {
              $ids[] = $article['target_id'];
            }
          }
          $ids[] = $data['node']->nid;
          $replacements[$original] = implode(',', $ids);
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_elife_hero_block_alter().
 */
function elife_collection_elife_hero_block_alter(&$content) {
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $nid = arg(1);
    if ($nid) {
      $node = node_load($nid);

      if ($node && 'elife_collection' === $node->type) {
        /* @var EntityDrupalWrapper $node */
        $node = entity_metadata_wrapper('node', $node);

        $variables = [
          'image_colour' => $node->field_elife_c_image_colour->value(),
          'image_path' => $node->field_elife_c_image->value()['uri'],
          'credit' => $node->field_elife_c_image_credit->value(),
          'title' => $node->field_elife_c_title->value()['safe_value'],
          'sub_title' => $node->field_elife_c_sub_title->value()['safe_value'],
        ];
        $content = theme('elife_hero_block', $variables);
      }
    }
  }
  elseif ('collections' === current_path()) {
    $variables = [
      'title' => t('Collections'),
      'image_colour' => 'dark',
      'image_path' => base_path() . drupal_get_path('module', 'elife_collection') . '/images/collections.png',
      'credit' => 'Nephrons captured with a 63X objective on a Nikon Confocal A1R microscope. 10.7554/eLife.04000',
    ];

    $content = theme('elife_hero_block', $variables);
  }
}

/**
 * Implements hook_elife_xmlsitemap_custom_links().
 */
function elife_collection_elife_xmlsitemap_custom_links() {
  return [
    'elife_collection' => [
      'collections',
    ],
  ];
}
