<?php
/**
 * @file
 * Code for the eLife: Collection feature.
 */

include_once 'elife_collection.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function elife_collection_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Implements template_preprocess_node().
 */
function elife_collection_preprocess_node(&$variables) {
  if ('elife_collection' === $variables['type']) {
    if (in_array($variables['view_mode'], ['teaser', 'elife_teaser_compact'])) {
      drupal_add_css(drupal_get_path('module', 'elife_collection') . '/css/collection-teaser.css');

      $curators = [];
      $curators_short = [];

      if (!empty($variables['elements']['#node']->field_elife_c_curators)) {
        foreach ($variables['elements']['#node']->field_elife_c_curators[LANGUAGE_NONE] as $curator) {
          $curator = node_load($curator['target_id']);

          if (empty($curator)) {
            continue;
          }

          $parts = [
            'first-name' => $curator->field_elife_pp_first_name[LANGUAGE_NONE][0]['safe_value'],
            'last-name' => $curator->field_elife_pp_last_name[LANGUAGE_NONE][0]['safe_value'],
          ];

          preg_match_all('/[A-Z]/', ucwords(strtolower($parts['first-name'])), $parts['initials']);
          $parts['initials'] = implode('', $parts['initials'][0]);

          $curators[] = [
            'data' => implode(' ', [$parts['first-name'], $parts['last-name']]),
            'class' => ['curator-list__item'],
          ];
          $curators_short[] = [
            'data' => implode(' ', [$parts['initials'], $parts['last-name']]),
            'class' => ['curator-list__item'],
          ];
        }
      }

      if (!empty($curators)) {
        $variables['elife_c_curators'] = theme('item_list', [
          'items' => $curators,
          'type' => 'ol',
          'title' => '',
          'attributes' => [
            'class' => [
              'collection-teaser__curator-list',
              'curator-list',
            ],
          ],
        ]);
      }

      if (!empty($curators_short)) {
        $variables['elife_c_curators_short'] = theme('item_list', [
          'items' => $curators_short,
          'type' => 'ol',
          'title' => '',
          'attributes' => [
            'class' => [
              'collection-teaser__curator-list',
              'curator-list',
            ],
          ],
        ]);
      }
    }
  }
}

/**
 * Implements hook_token_info().
 */
function elife_collection_token_info() {
  $info['tokens']['node']['elife-c-full-title'] = [
    'name' => t('Full title'),
    'description' => t('Full collection title.'),
  ];
  return $info;
}

/**
 * Implements hook_tokens().
 */
function elife_collection_tokens($type, $tokens, array $data = [], array $options = []) {
  $replacements = [];

  if ('node' === $type) {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'elife-c-full-title':
          $full_title = $data['node']->field_elife_c_title[LANGUAGE_NONE][0]['value'];

          if (!empty($data['node']->field_elife_c_sub_title[LANGUAGE_NONE][0]['value'])) {
            $full_title .= ': ' . $data['node']->field_elife_c_sub_title[LANGUAGE_NONE][0]['value'];
          }

          $replacements[$original] = $full_title;
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_elife_hero_block_alter().
 */
function elife_collection_elife_hero_block_alter(&$content) {
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $nid = arg(1);
    if ($nid) {
      $node = node_load($nid);

      if ($node && 'elife_collection' === $node->type) {
        /* @var EntityDrupalWrapper $node */
        $node = entity_metadata_wrapper('node', $node);

        $variables = [
          'image_colour' => $node->field_elife_c_image_colour->value(),
          'image_path' => $node->field_elife_c_image->value()['uri'],
          'credit' => $node->field_elife_c_image_credit->value(),
          'title' => $node->field_elife_c_title->value(),
          'sub_title' => $node->field_elife_c_sub_title->value(),
        ];
        $content = theme('elife_hero_block', $variables);
      }
    }
  }
  elseif ('collections' === current_path()) {
    $variables = [
      'title' => t('Collections'),
      'image_colour' => 'dark',
      'image_path' => base_path() . drupal_get_path('module', 'elife_collection') . '/images/collections.png',
      'credit' => 'Nephrons captured with a 63X objective on a Nikon Confocal A1R microscope. 10.7554/eLife.04000',
    ];

    $content = theme('elife_hero_block', $variables);
  }
}
