<?php
/**
 * @file
 * Code for the eLife - Lens links module.
 */

use eLife\EIF\ArticleVersion;

/**
 * Implements hook_node_view().
 */
function elife_lens_link_node_view($node, $view_mode, $langcode) {
  if ($node->type === 'elife_article_ver' && $view_mode === 'full') {
    $dto = elife_article_version_to_dto($node);
    if ($dto && $dto->getStatus() === 'VOR') {
      $path = drupal_get_path('module', 'elife_lens_link');
      drupal_add_css($path . '/css/elife-lens-link.css');
      drupal_add_js($path . '/js/elife-lens-link.js');
      drupal_add_js(array(
        'elife_lens_link' => array(
          // @todo - elife - nlisgo - consider making this a configuration option.
          'lensUri' => '//lens.elifesciences.org/' . $dto->getManuscriptId() .
          '/index.html',
        ),
      ), 'setting');
    }
  }
}
