<p><a href="http://elifesciences.org/category/biochemistry">Biochemistry</a></p>
<p><a href="http://elifesciences.org/category/biophysics-and-structural-biology">Biophysics and structural biology</a></p>
<p><a href="http://elifesciences.org/category/cell-biology">Cell biology</a></p>
<p><a href="http://elifesciences.org/category/computational-and-systems-biology">Computational and systems biology</a></p>
<p><a href="http://elifesciences.org/category/developmental-biology-and-stem-cells">Developmental biology &amp; stem cells</a></p>
<p><a href="http://elifesciences.org/category/ecology">Ecology</a></p>
<p><a href="http://elifesciences.org/category/epidemiology-and-global-health">Epidemiology &amp; global health</a></p>
<p><a href="http://elifesciences.org/category/genes-and-chromosomes">Genes &amp; chromosomes</a></p>
<p><a href="http://elifesciences.org/category/genomics-and-evolutionary-biology">Genomics &amp; evolutionary biology</a></p>
<p><a href="http://elifesciences.org/category/human-biology-and-medicine">Human biology &amp; medicine</a></p>
<p><a href="http://elifesciences.org/category/immunology">Immunology</a></p>
<p><a href="http://elifesciences.org/category/microbiology-and-infectious-disease">Microbiology &amp; infectious disease</a></p>
<p><a href="http://elifesciences.org/category/neuroscience">Neuroscience</a></p>
<p><a href="http://elifesciences.org/category/plant-biology">Plant biology</a></p>