<?php


/**
 * Implements hook_ctools_plugin_directory().
 */
function elife_templates_ctools_plugin_directory($owner, $plugin_type) {
  return "plugins/$plugin_type";
}

/**
 * Implements hook_theme().
 */
function elife_templates_theme($existing, $type, $theme, $path) {
  if ($type == 'module') {
    $template_path = drupal_get_path('module', 'elife_templates') . '/templates';
    $templates = array(
      'elife_hero' => array(
        'variables' => array(
          'title' => NULL,
          'title_detail' => NULL,
          'identifier' => NULL,
          'body' => NULL,
          'details' => NULL,
        ),
        'template' => 'elife_hero',
        'path' => $template_path,
      ),
      'elife_article_block' => array(
        'variables' => array(
          'identifier' => 'elife-article',
          'section' => NULL,
          'section_id' => NULL,
          'title' => NULL,
          'detail' => NULL,
        ),
        'template' => 'elife_article',
        'path' => $template_path,
      ),
      'elife_article_author_tooltip' => array(
        'variables' => array(
          'tooltip_name' => '',
          'affiliation' => NULL,
          'present_addy' => NULL,
          'contrib' => NULL,
          'other_footnotes' => NULL,
          'email' => NULL,
          'orcid' => NULL,
          'conflict' => NULL,
          'equal_contrib_group' => NULL,
          'deceased_footnote' => NULL,
        ),
        'template' => 'elife_article_author_tooltip',
        'path' => $template_path,
      ),
      'elife_article_detail' => array(
        'variables' => array(
          'identifier' => 'elife-article',
          'image' => NULL,
          'summary' => NULL,
          'author' => NULL,
          'doi' => NULL,
          'date' => NULL,
          'date_machine' => NULL,
        ),
        'template' => 'elife_article_detail',
        'path' => $template_path,
      ),
      'elife_article_repro_block' => array(
        'variables' => array(
          'identifier' => 'registered-report',
          'date' => NULL,
          'date_machine' => NULL,
          'title' => NULL,
          'details' => NULL,
        ),
        'template' => 'elife_article_repro_block',
        'path' => $template_path,
      ),
      'elife_article_repro_details' => array(
        'variables' => array(
          'author' => NULL,
          'source' => NULL,
          'doi' => NULL,
        ),
        'template' => 'elife_article_repro_details',
        'path' => $template_path,
      ),
      'elife_article_related' => array(
        'variables' => array(
          'title' => NULL,
          'authors' => NULL,
          'cats_and_heads' => NULL,
        ),
        'template' => 'elife_article_related',
        'path' => $path . '/templates',
      ),
      'elife_article_toolbox' => array(
        'variables' => array('node' => NULL),
      ),
      'elife_article_criticalrelation_block' => array(
        'variables' => array(
          'identifier' => 'critical-relations',
          'list_class' => array('critical-relation-list'),
          'reln_type' => NULL,
          'reln_type_id' => NULL,
          'reln_title' => NULL,
          'criticalrelations' => NULL,
        ),
        'template' => 'elife_article_criticalrelation_block',
        'path' => $path . '/templates',
      ),
      'elife_article_criticalrelation' => array(
        'variables' => array(
          'identifier' => 'critical-relation',
          'other_title' => NULL,
          'other_authors' => NULL,
          'other_impact_statement' => NULL,
          'other_citeas' => NULL,
          'other_doi_link' => NULL,
        ),
        'template' => 'elife_article_criticalrelation',
        'path' => $path . '/templates',
      ),
      'elife_cover' => array(
        'variables' => array(
          'title' => NULL,
          'additional_classes' => NULL,
          'read_more' => NULL,
          'caption' => NULL,
        ),
        'template' => 'elife_cover',
        'path' => $path . '/templates',
      ),
      'elife_front_matter' => array(
        'variables' => array(
          'title' => NULL,
          'display' => NULL,
          'image' => NULL,
          'section' => NULL,
          'section_name' => NULL,
        ),
        'template' => 'elife_front_matter',
        'path' => $path . '/templates',
      ),
      'elife_front_matter_wrapper' => array(
        'variables' => array(
          'cover' => NULL,
          'front_matter_col_1' => NULL,
          'front_matter_col_2' => NULL,
        ),
        'template' => 'elife_front_matter_wrapper',
        'path' => $path . '/templates',
      ),
    );
    return $templates;
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function elife_templates_theme_registry_alter(&$theme_registry) {
  $theme_registries = array(
    'views_view_unformatted',
    'semanticviews_view_unformatted',
  );
  foreach ($theme_registries as $tr) {
    if (isset($theme_registry[$tr])) {
      $theme_registry[$tr]['path'] = drupal_get_path('module', 'elife_templates') . '/templates';
    }
  }
}

/**
 * Implements hook_preprocess_semanticviews_view_unformatted().
 */
function elife_templates_preprocess_semanticviews_view_unformatted(&$variables) {
  $view = $variables['view'];
  foreach ($view->result as $delta => $item) {
    if (isset($item->nid)) {
      $variables['row_element'] = 'div';
      $variables['row_attributes'][$delta]['class'][] = 'contextual-links-region';
      $element = element_info('contextual_links');
      $element['#contextual_links'] = array(
        'node' => array(
          'node',
          array($item->nid),
        ),
      );
      $variables['contextual_node'][$delta] = drupal_render($element);
    }
  }
}

/**
 * Implements template_preprocess_html().
 */
function elife_templates_preprocess_html(&$variables) {
  if (count(array_intersect([
    'node-type-elife-collection',
    'page-collections',
  ], $variables['classes_array']))) {
    drupal_add_css(drupal_get_path('module', 'elife_templates') . '/css/collection.css');
  }
}

function elife_templates_article_page_markup_assets() {
  $cache = &drupal_static(__FUNCTION__, FALSE);
  if (!$cache) {
    // Add js and css needed to help render the markup once it's in place.
    drupal_add_js(drupal_get_path('module', 'elife_templates') . '/js/elife_article_figures.js');
    drupal_add_js(drupal_get_path('module', 'elife_templates') . '/js/elife_article_tables.js');
    drupal_add_js(drupal_get_path('module', 'elife_templates') . '/js/elife_article_reference_popup.js');

    $cache = TRUE;
  }
  return $cache;
}
