<?php
/**
 * @file
 * Code for the eLife - Early careers.
 */

use Drupal\elife_article\ElifeArticleVersion;

include_once 'elife_early_careers.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function elife_early_careers_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_menu().
 */
function elife_early_careers_menu() {
  return [
    'careers' => [
      'description' => 'Preview the early careers content.',
      'page callback' => 'elife_early_careers_page_load',
      'access callback' => TRUE,
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function elife_early_careers_theme($existing, $type, $theme, $path) {
  if ($type == 'module') {
    $path = drupal_get_path('module', 'elife_early_careers') . '/templates';
    $templates = [
      'elife_early_careers' => [
        'variables' => [
          'spotlight' => NULL,
          'profiles' => NULL,
          'presentation_links_title' => NULL,
          'presentation_links' => NULL,
        ],
        'template' => 'elife_early_careers',
        'path' => $path,
      ],
      'elife_early_careers_nav' => [
        'variables' => [],
        'template' => 'elife_early_careers_nav',
        'path' => $path,
      ],
      'elife_early_careers_profile' => [
        'variables' => [
          'profile_attributes' => NULL,
          'title' => NULL,
          'image_extra' => NULL,
          'profile_title' => NULL,
          'affiliation' => NULL,
          'coi' => NULL,
        ],
        'template' => 'elife_early_careers_profile',
        'path' => $path,
      ],
      'elife_early_careers_profile_wrapper' => [
        'variables' => [
          'profiles' => NULL,
        ],
        'template' => 'elife_early_careers_profile_wrapper',
        'path' => $path,
      ],
      'elife_early_careers_profile_extra' => [
        'variables' => [
          'title' => NULL,
          'image_extra' => NULL,
          'details' => NULL,
          'additional' => NULL,
          'additional_label' => NULL,
        ],
        'template' => 'elife_early_careers_profile_extra',
        'path' => $path,
      ],
    ];
    return $templates;
  }
}

/**
 * Implements template_preprocess_node().
 */
function elife_early_careers_preprocess_node(&$variables) {
  if ('elife_early_careers_spotlight' === $variables['type'] && 'teaser' === $variables['view_mode']) {
    $node = $variables['node'];
    $reference = node_load($node->field_elife_s_reference[LANGUAGE_NONE][0]['target_id']);

    $path = 'node/' . $reference->nid;

    switch ($reference->type) {
      case 'elife_article_reference':
        $article_version = elife_article_reference_get_article_version($reference);
        if (!$article_version) {
          break;
        }

        $categories = ElifeArticleVersion::getCategories($article_version->field_elife_a_article_version_id[LANGUAGE_NONE][0]['value']);

        if (!empty($categories['display-channel'])) {
          $heading = $categories['display-channel'][0];
        }

        $path = 'node/' . $article_version->nid;

        break;
      case 'elife_collection':
        $heading = t('Collections');
        $view_more_text = 'View more collections';
        $view_more_path = 'collections';
        break;
      case 'elife_early_careers_interview':
        $heading = t('Interviews');
        $view_more_text = 'View more interviews';
        $view_more_path = 'early-careers-interviews';
        break;
      case 'elife_event':
        $heading = t('Events');
        $view_more_text = 'View more events';
        $view_more_path = 'events';
        break;
      case 'elife_news_article':
        $heading = t('News');
        $view_more_text = 'View more news';
        $view_more_path = 'news';
        break;
      case 'elife_podcast':
        $heading = t('Podcasts');
        $view_more_text = 'View more podcasts';
        $view_more_path = 'podcast';
        break;
      default:
        // This is a bug if reached.
        return;
    }

    $variables['elife_s_heading'] = '<h2 class="ec-section__heading">' . $heading . '</h2>';

    $variables['elife_s_title'] = '<h3 class="ec-section--latest__item-title">' . l($node->field_elife_title[LANGUAGE_NONE][0]['safe_value'], $path, ['html' => TRUE]) . '</h3>';

    if (!empty($view_more_text)) {
      $variables['elife_s_view_more'] = l(t($view_more_text), $view_more_path, ['attributes' => ['class' => ['ec-section--latest__more-link']]]);
    }
  }
}

/**
 * Return the content for the early careers page.
 *
 * @return string
 *   early careers page output
 */
function elife_early_careers_page_load() {
  $path = drupal_get_path('module', 'elife_early_careers');
  drupal_add_js($path . '/js/elife_early_careers.js', ['scope' => 'footer']);
  drupal_add_js(['elifeEarlyCareers' => ['moduleFolder' => drupal_get_path('module', 'elife_early_careers')]], 'setting');
  drupal_add_css($path . '/css/early_careers.css');
  $variables = [];
  $variables['spotlight'] = elife_early_careers_spotlight();
  $variables['profiles'] = elife_early_careers_profiles_load();

  $presentation_menu_links = [
    'eLife-news/Early-career-researchers-Hangout-On-Air-with-eLife' => 'Early-career researchers Hangout On Air with eLife (December 22, 2014)',
    'eLife-news/Four-more-early-career-authors-invited-to-participate-in-a-meeting-at-one-of-eLifes-founders' => 'Four more early-career authors invited to participate in a meeting hosted by one of eLife’s founders (December 17, 2014)',
    'elife-news/Junior-scientists-in-Hawaii-California-and-Beijing-Hangout-On-Air-with-eLife' => 'Junior scientists in Hawaii, California and Beijing Hangout On Air with eLife (June 1, 2014)',
    'eLife-recognises-early-career-researchers' => 'eLife recognises early-career researchers; Academic editors showcase five outstanding studies (May 22, 2014)',
    'Early-career-authors-present-their-eLife-works-at-HHMI' => 'Early career authors present their eLife works at HHMI (May 16, 2014)',
    'elife-news/elife-selects-four-outstanding-papers-showcases-early-career-investigators' => 'eLife selects four outstanding papers, showcases early-career investigators (October 23, 2013)',
  ];

  if (!empty($presentation_menu_links)) {
    $variables['presentation_links_title'] = 'Read more about the eLife-sponsored presentation series';

    foreach ($presentation_menu_links as $path => $text) {
      $presentation_menu_links[$path] = [
        'data' => l($text, $path),
        'class' => ['ec-section--presentations__list_item'],
      ];
    }
    $variables['presentation_links'] = theme('item_list', array(
      'type' => 'ul',
      'items' => $presentation_menu_links,
      'attributes' => ['class' => ['ec-section--presentations__list']],
      'div_class' => 'no',
    ));
  }

  return theme('elife_early_careers', $variables);
}

/**
 * Return the profiles sections content.
 *
 * @return string
 *   profiles output
 */
function elife_early_careers_profiles_load() {
  $variables = [];
  $profiles = elife_person_profile_get_view('early-careers');

  if (!empty($profiles)) {
    $variables['profiles'] = $profiles;
  }

  return theme('elife_early_careers_profile_wrapper', $variables);
}

/**
 * Return the early careers spotlight items.
 *
 * @return string|bool
 *   Spotlights output.
 */
function elife_early_careers_spotlight() {
  return elife_person_profile_views_embed_view('elife_early_careers_spotlight');
}

/**
 * Prepare the early careers nav.
 */
function elife_early_careers_nav_load() {
  $variables = [];

  return theme('elife_early_careers_nav', $variables);
}

/**
 * Implements hook_page_alter().
 */
function elife_early_careers_page_alter(&$page) {
  if (current_path() === 'careers') {
    $page['page_top']['elife_early_careers_nav'] = [
      '#weight' => 10,
      '#markup' => elife_early_careers_nav_load(),
    ];
  }
}

/**
 * Implements hook_preprocess_html().
 */
function elife_early_careers_preprocess_html(&$vars) {
  if (current_path() === 'careers') {
    // @todo - elife - revisit this code using metatag

    // There is an issue with the HTML title not being set correctly.
    // This has been experienced on the about page.
    // This has been introduced since metatag module enabled.
    $title_vars = [
      t('Early careers: eLife showcases junior investigators and their work'),
      variable_get('site_name'),
    ];

    $vars['head_title'] = implode(' | ', $title_vars);
  }
}

/**
 * Implements hook_elife_xmlsitemap_custom_links().
 */
function elife_early_careers_elife_xmlsitemap_custom_links() {
  return [
    'elife_early_careers' => [
      'careers',
    ],
  ];
}
