<?php
/**
 * @file
 * Code for the eLife: Hero Block feature.
 */

include_once 'elife_hero_block.features.inc';

const ELIFE_HERO_BLOCK_CTA_TEXT_DEFAULT = 'Sign up to receive weekly alerts on new content from eLife';
const ELIFE_HERO_BLOCK_CTA_LINK_TEXT_DEFAULT = 'Sign up';
const ELIFE_HERO_BLOCK_CTA_LINK_TEXT_URL_DEFAULT = 'http://crm.elifesciences.org/crm/civicrm/profile/create?reset=1&gid=18';

/**
 * Implements hook_ctools_plugin_directory().
 */
function elife_hero_block_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_theme().
 */
function elife_hero_block_theme($existing, $type, $theme, $path) {
  if ('module' === $type) {
    $path = drupal_get_path('module', 'elife_hero_block');
    $templates = [
      'elife_hero_block' => [
        'variables' => [
          'image_colour' => 'light',
          'image_path' => NULL,
          'credit' => NULL,
          'title' => NULL,
          'sub_title' => NULL,
          'cta_text' => ELIFE_HERO_BLOCK_CTA_TEXT_DEFAULT,
          'cta_link_text' => ELIFE_HERO_BLOCK_CTA_LINK_TEXT_DEFAULT,
          'cta_link_url' => ELIFE_HERO_BLOCK_CTA_LINK_TEXT_URL_DEFAULT,
          'player' => NULL,
          'player_autoplay' => FALSE,
          'content_column_items' => [],
        ],
        'template' => 'elife_hero_block',
        'path' => $path . '/templates',
      ],
    ];
    return $templates;
  }
}
