<?php
/**
 * @file
 * Code for the eLife News feature.
 */

include_once 'elife_news.features.inc';

/**
 * Implements template_preprocess_node().
 */
function elife_news_preprocess_node(&$variables) {
  if ('elife_news_article' === $variables['type'] && 'teaser' === $variables['view_mode']) {
    drupal_add_css(drupal_get_path('module', 'elife_news') . '/css/news-article-teaser.css');
  }
}

/**
 * Implements hook_elife_body_field().
 */
function elife_news_elife_body_field() {
  return [
    'elife_news_article' => 'field_elife_n_text',
  ];
}
