<?php
/**
 * @file
 * Code for the eLife News feature.
 */

include_once 'elife_news.features.inc';

/**
 * Implements hook_node_view().
 */
function elife_news_node_view($node, $view_mode, $langcode) {
  if ('elife_news_article' === $node->type && 'teaser' === $view_mode) {
    $node->content['#attached']['css'][] = drupal_get_path('module', 'elife_news') . '/css/news-article-teaser.css';
  }
}

/**
 * Implements hook_elife_body_field().
 */
function elife_news_elife_body_field() {
  return [
    'elife_news_article' => 'field_elife_n_text',
  ];
}

/**
 * Implements hook_elife_xmlsitemap_custom_links().
 */
function elife_news_elife_xmlsitemap_custom_links() {
  return [
    'elife_news' => [
      'elife-news',
    ],
  ];
}
