<?php
/**
 * @file
 * elife_header.install
 */

/**
 * Implements hook_enable().
 */
function elife_header_enable() {

  // Remove all blocks from "eLife Bar" Region.
  $query = db_update('block')
    ->fields(array(
      'status' => 0,
      'weight' => 0,
      'region' => '-1',
      'visibility' => 0,
      'pages' => '',
      'cache' => -1,
    ))
    ->condition('region', 'elife_bar')
    ->condition('theme', 'elife')
    ->execute();
}
