<?php
/**
 * @file
 * elife_article_assets.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function elife_article_assets_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_elife_aa_striking_figure'
  $field_bases['field_elife_aa_striking_figure'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_elife_aa_striking_figure',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_elife_aa_striking_image'
  $field_bases['field_elife_aa_striking_image'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_elife_aa_striking_image',
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 0,
      'uri_scheme' => 'public',
    ),
    'translatable' => 0,
    'type' => 'image',
  );

  return $field_bases;
}
