<?php
/**
 * @file
 * Code for the eLife: Article Assets feature.
 */

use Drupal\elife_article\ElifeArticleVersion;

include_once 'elife_article_assets.features.inc';

/**
 * Get the image style path for the article striking image.
 *
 * @param string $article_id
 *   Article Id.
 * @param string $image_style
 *   Image style preset
 * @param string $figure
 *   Preferred figure number
 *
 * @return string
 *   Image style path
 */
function elife_article_assets_striking_image_path($article_id, $image_style = 'elife_striking_image', $figure = NULL) {
  if ($image_style = image_style_load($image_style)) {
    $id_query = new EntityFieldQuery();
    $id_query->entityCondition('entity_type', 'node');
    $id_query->entityCondition('bundle', 'elife_article_assets');
    $id_query->fieldCondition('field_elife_a_article_id', 'value', $article_id, '=');
    $id_query->range(0, 1);
    $ids = $id_query->execute();
    if (!empty($ids['node'])) {
      $nids = array_keys($ids['node']);
      $article_assets = node_load($nids[0]);
      /* @var EntityDrupalWrapper $ewrapper */
      if ($ewrapper = entity_metadata_wrapper('node', $article_assets)) {
        if ($image_properties = $ewrapper->field_elife_aa_striking_image->value()) {
          $image_uri = $image_properties['uri'];
          $image_style_path = image_style_path($image_style['name'], $image_uri);
          $success = file_exists($image_style_path) || image_style_create_derivative($image_style, $image_uri, $image_style_path);
          if ($success) {
            return $image_style_path;
          }
        }
        if (empty($figure) && $striking_figure = $ewrapper->field_elife_aa_striking_figure->value()) {
          $figure = $striking_figure;
        }
      }
    }
    if (empty($figure)) {
      $figure = '1';
    }
    // @todo - elife - nlisgo - this will need to be refactored once we know
    // where article assets will be hosted.
    if (is_numeric($figure)) {
      $figure = 'f' . str_pad($figure, 3, "0", STR_PAD_LEFT);
    }
    $url = sprintf('http://cdn.elifesciences.org/elife-articles/%s/jpg/elife%s%s.jpg', $article_id, $article_id, $figure);
    if ($image_uri = imagecache_external_generate_path($url)) {
      $image_style_path = image_style_path($image_style['name'], $image_uri);
      $success = file_exists($image_style_path) || image_style_create_derivative($image_style, $image_uri, $image_style_path);
      if ($success) {
        return $image_style_path;
      }
    }
  }
}
