<?php

/**
 * @file
 * Code for the eLife: Content Alerts module.
 */

const ELIFE_CONTENT_ALERT_DEFAULT_ID = 'article_rev140402';
const ELIFE_CONTENT_ALERT_DEFAULT_GID = '18';

/**
 * Sign up form.
 */
function elife_content_alerts_sign_up_form($form, &$form_state, $custom_6 = NULL, $gid = NULL) {
  if (empty($custom_6)) {
    $custom_6 = ELIFE_CONTENT_ALERT_DEFAULT_ID;
  }
  if (empty($gid)) {
    $gid = ELIFE_CONTENT_ALERT_DEFAULT_GID;
  }

  $form['#attributes'] = array('class' => 'elife-sign-up-form');
  $form['#action'] = 'http://crm.elifesciences.org/crm/civicrm/profile/create?reset=1&gid=' . $gid;

  $form['#method'] = 'post';
  $form['reset'] = array(
    '#type' => 'hidden',
    '#value' => 1,
  );
  $form['gid'] = array(
    '#type' => 'hidden',
    '#value' => $gid,
  );

  $form['custom_6'] = array(
    '#type' => 'hidden',
    '#value' => $custom_6,
  );
  $form['_qf_Edit_next'] = array(
    '#type' => 'hidden',
    '#value' => 'Save',
  );
  $form['email-3'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('type your email address...'),
    ),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('SIGN UP'),
  );
  return $form;
}

/**
 * Implements hook_block_info().
 */
function elife_content_alerts_block_info() {
  $blocks['elife_content_alerts_sign_up'] = array(
    'info' => t('eLife: Content alerts signup'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function elife_content_alerts_block_view($delta = '') {
  switch ($delta) {
    case 'elife_content_alerts_sign_up':
      $sign_up_form = drupal_get_form('elife_content_alerts_sign_up_form');
      return array(
        'subject' => NULL,
        'content' => drupal_render($sign_up_form),
      );
  }
}
