<?php
/**
 * @file
 * Code for the eLife: Early Careers Interviews feature.
 */

include_once 'elife_early_careers_interviews.features.inc';

/**
 * Implements hook_custom_theme().
 */
function elife_early_careers_interviews_custom_theme() {
  if ($term = menu_get_object('taxonomy_term', 2)) {
    if ('elife_i_series' === $term->vocabulary_machine_name) {
      // We can't use a page_theme wildcare as the interviews use the 'elife' theme.
      return 'elife_newlook';
    }
  }
}

/**
 * Implements hook_node_view().
 */
function elife_early_careers_interviews_node_view($node, $view_mode, $langcode) {
  if (
    'elife_early_careers_interview' === $node->type
    &&
    in_array($view_mode, ['teaser', 'elife_teaser_compact'])
  ) {
    $node->content['#attached']['css'][] = drupal_get_path('module', 'elife_collection') . '/css/collection-teaser.css';
  }
}

/**
 * Implements hook_elife_body_field().
 */
function elife_early_careers_interviews_elife_body_field() {
  return [
    'elife_early_careers_interview' => 'field_elife_i_text',
  ];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 */
function elife_early_careers_interviews_form_node_form_alter(&$form, &$form_state) {
  switch ($form['#node']->type) {
    case 'elife_early_careers_interview':
      $form['field_elife_title']['#access'] = FALSE;
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for taxonomy_form_term().
 */
function elife_early_careers_interviews_form_taxonomy_form_term_alter(&$form, &$form_state) {
  switch ($form['#vocabulary']->machine_name) {
    case 'elife_i_series':
      $form['field_elife_title']['#access'] = FALSE;
  }
}

/**
 * Implements hook_elife_hero_block_alter().
 */
function elife_early_careers_interviews_elife_hero_block_alter(&$content) {
  if ($term = menu_get_object('taxonomy_term', 2)) {
    $variables = [
      'title' => $term->field_elife_is_title[LANGUAGE_NONE][0]['safe_value'],
      'sub_title' => !empty($term->field_elife_is_sub_title[LANGUAGE_NONE]) ? $term->field_elife_is_sub_title[LANGUAGE_NONE][0]['safe_value'] : '',
      'image_colour' => $term->field_elife_is_image_colour[LANGUAGE_NONE][0]['value'],
      'image_path' => $term->field_elife_is_image[LANGUAGE_NONE][0]['uri'],
      'credit' => !empty($term->field_elife_is_image_credit[LANGUAGE_NONE]) ? $term->field_elife_is_image_credit[LANGUAGE_NONE][0]['safe_value'] : '',
    ];

    $content = theme('elife_hero_block', $variables);
  }
}
